# Let's see if a change to workflow definition triggers a full build across all services.

name: Reusable Build and Manifest Update

on:
  workflow_call:
    inputs:
      service-name: { type: string, required: true }
      context-path: { type: string, required: true }
    secrets:
      GIT_PAT: { required: true }
      DOCKER_USERNAME: { required: true }
      DOCKER_PASSWORD: { required: true }

env:
  DOCKER_REGISTRY: ghcr.io # Update with your registry
  IMAGE_NAME: ${{ github.repository_owner }}/${{ inputs.service-name }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # <--- This gives the GITHUB_TOKEN the power to push images
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and Test (Reactor)
        run: mvn clean install -pl ${{ inputs.service-name }} -am -DskipTests

      # --fail-at-end ensures target/surefire-reports are generated even if tests fail
      - name: Build and Run Tests
        run: mvn test --batch-mode --fail-at-end

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          # Use a unique name for each matrix combination/module
          name: test-results-${{ inputs.service-name }}
          path: "**/target/*-reports/*.xml"
          if-no-files-found: ignore

################### Disabling Integration TESTS  FOR NOW .......!!!!!
#      # Use 'verify' instead of 'test' to trigger the Failsafe plugin
#      - name: Build and Run All Tests
#        run: mvn clean verify --batch-mode
#
#      # Publish both Surefire (Unit) and Failsafe (Integration) results
#      - name: Publish Test Report
#        if: success() || failure()
#        uses: ScalableCapital/action-surefire-report@v2
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          # Tells the action to look for both sets of XML reports
#          report_paths: |
#            **/target/surefire-reports/TEST-*.xml
#            **/target/failsafe-reports/TEST-*.xml

      - name: Login to Container Registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.context-path }}
          file: ${{ inputs.context-path }}/Dockerfile
          push: true
          # Tags the image with the git commit hash for traceability
          # tags: ${{ secrets.DOCKER_USERNAME }}/${{ inputs.service-name }}:${{ github.sha }}
          tags: |
            ghcr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ghcr.io/${{ env.IMAGE_NAME }}:latest

#  update-manifest:
#    needs: docker-build-push
#    runs-on: ubuntu-latest
#    steps:
#      - name: Update Manifest Repo
#        run: |
#          git clone --depth 1 https://x-access-token:${{ secrets.GIT_PAT }}@github.com/my-org/manifest-repo.git
#          cd manifest-repo/environments/${{ github.ref_name }}/${{ inputs.service-name }}
#          yq -i '.image.tag = "${{ github.sha }}"' values.yaml
#          git config user.name "CI-Bot"
#          git commit -am "Update ${{ inputs.service-name }} to ${{ github.sha }}"
#          git push
